version: "3.8"

services:
  calc-web:
    build:
      context: calc-web
    ports:
      - 8080:80
    command: [nginx-debug, "-g", "daemon off;"]
  #calc-api-db:
  #image: postgres:12.8-alpine
  calc-api:
    build:
      context: calc-api
    environment:
      - PORT=80
    ports:
      - 8081:80
