version: "3.8"

services:
  calc-web:
    container_name: calc-web
    build:
      context: calc-web
    ports:
      - 8080:80
    command: [nginx-debug, "-g", "daemon off;"]
  #calc-api-db:
  #image: postgres:12.8-alpine
  calc-api:
    container_name: calc-api
    build:
      context: calc-api
    environment:
      - PORT=80
      - SQS_ENDPOINT=http://calc-jobs-queue:9324
      - QUEUE_ENDPOINT=http://calc-jobs-queue:9324/queue/default
    ports:
      - 8081:80
  calc-jobs-queue:
    container_name: calc-jobs-queue
    image: roribio16/alpine-sqs
    ports:
      - 9324:9324
      - 9325:9325
    # volumes:
    #   - ./calc-jobs-queue/elasticmq.conf:/opt/config/elasticmq.conf
  calc-worker:
    build: ./calc-worker
    environment:
      - SQS_ENDPOINT=http://calc-jobs-queue:9324
      - QUEUE_ENDPOINT=http://calc-jobs-queue:9324/queue/default
