version: "3.8"

services:
  calc-web:
    container_name: calc-web
    build:
      context: calc-web
    image: dlemvigh/calc-web
    depends_on:
      - calc-api
    ports:
      - 8080:80
    command: [nginx-debug, "-g", "daemon off;"]
  calc-api:
    container_name: calc-api
    build:
      context: calc-api
    image: dlemvigh/calc-api
    environment:
      - PORT=80
      - SQS_ENDPOINT=http://calc-queue:9324
      - QUEUE_ENDPOINT=http://calc-queue:9324/queue/default
    ports:
      - 8081:80
    depends_on:
      - calc-queue
    networks:
      - frontend
      - backend
  calc-web-next:
    container_name: calc-web-next
    build:
      context: calc-web-next
    image: dlemvigh/calc-web-next
    depends_on:
      - calc-api
    ports:
      - 3000:3000
    environment:
      - API_ENDPOINT=localhost:3000/api
      - API_ENDPOINT_SSR=calc-api:80
    networks:
      - frontend
  calc-queue:
    container_name: calc-queue
    image: roribio16/alpine-sqs
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - ./calc-jobs-queue/elasticmq.conf:/opt/config/elasticmq.conf
    networks:
      - backend
  calc-worker:
    build: ./calc-worker
    image: dlemvigh/calc-worker
    environment:
      - SQS_ENDPOINT=http://calc-queue:9324
      - QUEUE_ENDPOINT=http://calc-queue:9324/queue/default
      - API_ENDPOINT=http://calc-api:80
      - POLLING_INTERVAL=1000
      - DEBUG=false
    networks:
      - backend
    depends_on:
      - calc-queue
      - calc-api
    deploy:
      mode: replicated
      replicas: 1
  calc-worker-dotnet:
    build: ./calc-worker-dotnet
    image: dlemvigh/calc-worker-dotnet
    environment:
      - SQS_ENDPOINT=http://calc-queue:9324
      - QUEUE_ENDPOINT=http://calc-queue:9324/queue/default
      - API_ENDPOINT=http://calc-api:80
      - POLLING_INTERVAL=1000
      - DEBUG=false
    networks:
      - backend
    depends_on:
      - calc-queue
      - calc-api
    deploy:
      mode: replicated
      replicas: 1
  cypress:
    image: "cypress/included:9.2.0"
    profiles:
      - ci
    depends_on:
      - calc-web
      - calc-worker-dotnet
    environment:
      - CYPRESS_baseUrl=http://calc-web:80
    networks:
      - frontend
    working_dir: /e2e
    volumes:
      - "./integration-test:/e2e"
networks:
  frontend:
  backend:
