apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o chart
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: calc-web
  name: calc-web
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
      nodePort: 30080
  selector:
    io.kompose.service: calc-web
  type: NodePort
status:
  loadBalancer: {}
