apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o chart
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: calc-web
  name: calc-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: calc-web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml -o chart
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: calc-web
    spec:
      containers:
        - args:
            - nginx-debug
            - -g
            - daemon off;
          image: dlemvigh/calc-web
          name: calc-web
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
