version: "3.8"

services:
  calc-web:
    extends:
      file: ../docker-compose.yml
      service: calc-web
    build:
      args:
        - REACT_APP_BASE_URL=calc-api
  calc-api:
    extends:
      file: ../docker-compose.yml
      service: calc-api
  calc-queue:
    extends:
      file: ../docker-compose.yml
      service: calc-queue
  calc-worker:
    extends:
      file: ../docker-compose.yml
      service: calc-worker
    deploy:
      replicas: 1
  cypress:
    image: "cypress/included:8.4.1"
    depends_on:
      - calc-web
      - calc-worker
    environment:
      - CYPRESS_baseUrl=http://calc-web:80
    working_dir: /e2e
    volumes:
      - "$PWD:/e2e"
