apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\dev\calc-microservice\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: calc-api
  name: calc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: calc-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\dev\calc-microservice\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: calc-api
    spec:
      containers:
        - env:
            - name: PORT
              value: "80"
            - name: QUEUE_ENDPOINT
              value: http://calc-queue.default.svc.cluster.local:9324/queue/default
            - name: SQS_ENDPOINT
              value: http://calc-queue.default.svc.cluster.local:9324
          image: calc-microservice_calc-api
          imagePullPolicy: IfNotPresent
          name: calc-api
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
