apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\dev\calc-microservice\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: calc-queue
  name: calc-queue
spec:
  ports:
  - name: "9324"
    port: 9324
    targetPort: 9324
  - name: "9325"
    port: 9325
    targetPort: 9325
  selector:
    io.kompose.service: calc-queue
status:
  loadBalancer: {}
