apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: calc-queue
  name: calc-queue
spec:
  ports:
    - name: "9324"
      port: 9324
      targetPort: 9324
      nodePort: 30004
    - name: "9325"
      port: 9325
      targetPort: 9325
      nodePort: 30005
  selector:
    io.kompose.service: calc-queue
  type: NodePort
status:
  loadBalancer: {}
