apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: calc-api
  name: calc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: calc-api
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: calc-api
    spec:
      containers:
        - name: calc-api
          image: calc-microservice_calc-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: QUEUE_ENDPOINT
              value: http://calc-queue.default.svc.cluster.local:9324/queue/default
            - name: SQS_ENDPOINT
              value: http://calc-queue.default.svc.cluster.local:9324
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
