apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: calc-web
  name: calc-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: calc-web
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: calc-web
    spec:
      containers:
        - name: calc-web
          image: calc-microservice_calc-web
          imagePullPolicy: IfNotPresent
          args:
            - nginx-debug
            - -g
            - daemon off;
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
