apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: calc-api
  name: calc-api
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 80
      nodePort: 30081
  selector:
    io.kompose.service: calc-api
  type: NodePort
status:
  loadBalancer: {}
