apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-queue
  labels:
    io.kompose.service: calc-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: calc-queue
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: calc-queue
    spec:
      containers:
        - name: calc-queue
          image: roribio16/alpine-sqs
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9324
            - containerPort: 9325
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
