apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: calc-worker
  name: calc-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: calc-worker
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: calc-worker
    spec:
      containers:
        - name: calc-worker
          image: calc-microservice_calc-worker
          imagePullPolicy: IfNotPresent
          env:
            - name: API_ENDPOINT
              value: http://calc-api.default.svc.cluster.local:80
            - name: QUEUE_ENDPOINT
              value: http://calc-queue.default.svc.cluster.local:9324/queue/default
            - name: SQS_ENDPOINT
              value: http://calc-queue.default.svc.cluster.local:9324
          resources: {}
      restartPolicy: Always
status: {}
