apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: calc-web
  name: calc-web
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
      nodePort: 30080
  selector:
    io.kompose.service: calc-web
  type: NodePort
status:
  loadBalancer: {}
