apiVersion: v1
kind: Service
metadata:
  name: calc-web
  labels:
    app: calc-web
spec:
  ports:
    - port: 80
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-web
  labels:
    app: calc-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc-web
  template:
    metadata:
      labels:
        app: calc-web
    spec:
      containers:
        - name: calc-web
          image: calc-microservice_calc-web
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              port: 80
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 1
