name: CI (self-hosted)

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build containers
        run: docker-compose build
      - name: Cypress
        run: docker-compose run cypress
      - name: Cypress (remove videos)
        uses: JesseTG/rm@v1.0.3
        if: ${{ always() }}
        with:
          path: integration-test/cypress/videos
      - name: Cypress (remove screenshots)
        uses: JesseTG/rm@v1.0.3
        if: ${{ always() }}
        with:
          path: integration-test/cypress/screenshots
      - name: Stop
        run: docker-compose down
