name: CI

on:
  workflow_dispatch:    
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build containers
        run: docker-compose build
      - name: Cypress
        run: docker-compose run cypress
      - name: Cypress (fix-ownership)
        run: sudo chown $(id -u):$(id -g) -R cypress
        working-directory: integration-test
      - name: Stop
        run: docker-compose down
