name: Visual regressions

on:
  workflow_dispatch:    
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  visual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build containers
        run: docker-compose build calc-web-next-playwright
      - name: Build containers
        run: docker-compose run calc-web-next-playwright
